name: Run CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Scalafmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup coursier cache
        uses: coursier/cache-action@v8.0
      - uses: VirtusLab/scala-cli-setup@v1
      - name: Check formatting
        run: scala-cli --power fmt --check .

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup coursier cache
        uses: coursier/cache-action@v8.0
      - uses: VirtusLab/scala-cli-setup@v1
#      - name: Run tests (Scala LTS)
#        run: scala-cli --power test .
      - name: Run tests (Scala Next)
        run: scala-cli --power test . -S 3.8.2
      - name: Test documentation
        run: scala-cli --power doc .
