name: Publish
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup coursier cache
        uses: coursier/cache-action@v8.0
      - uses: VirtusLab/scala-cli-setup@v1.12.3
      - name: Run tests
        run: scala-cli --power test .
      - name: Publish
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        run: |
          scala-cli --power --verbose publish . \
            --user "env:SONATYPE_USERNAME" \
            --password "env:SONATYPE_PASSWORD" \
            --secret-key "env:PGP_PRIVATE_KEY" \
            --secret-key-password "env:PGP_PASSPHRASE"
